# Generated by Django 2.0.7 on 2018-07-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImovelComercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_available', models.BooleanField(default=True)),
                ('valor_condominio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_iptu', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quartos', models.PositiveSmallIntegerField(blank=True)),
                ('banheiros', models.PositiveSmallIntegerField(blank=True)),
                ('salas', models.PositiveSmallIntegerField(blank=True)),
                ('vagas_garagem', models.PositiveSmallIntegerField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('tipo_imovel', models.CharField(choices=[('SALA', 'Sala'), ('LOJA', 'Loja'), ('GALERIA', 'Galeria')], max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImovelResidencial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_available', models.BooleanField(default=True)),
                ('valor_condominio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_iptu', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quartos', models.PositiveSmallIntegerField(blank=True)),
                ('banheiros', models.PositiveSmallIntegerField(blank=True)),
                ('salas', models.PositiveSmallIntegerField(blank=True)),
                ('vagas_garagem', models.PositiveSmallIntegerField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('tipo_imovel', models.CharField(choices=[('APT', 'Apartamento'), ('CASA', 'Casa'), ('COBERTURA', 'Cobertura')], max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('documento', models.CharField(max_length=20)),
                ('tel1', models.CharField(blank=True, max_length=20)),
                ('tel2', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='imovelresidencial',
            name='proprietario',
            field=models.OneToOneField(on_delete='CASCADE', related_name='imovelresidencial_proprietario', to='imobiletto.Proprietario'),
        ),
        migrations.AddField(
            model_name='imovelcomercial',
            name='proprietario',
            field=models.OneToOneField(on_delete='CASCADE', related_name='imovelcomercial_proprietario', to='imobiletto.Proprietario'),
        ),
    ]
